# Run a Python Hello World!

trigger:
- main

pool:
  name: Default

steps:

  - script: |
      python --version
      pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python hello_world.py
    displayName: 'Run hello_world.py'
